pipeline {
//where to execute
  
   agent any
  tools {nodejs "node"}
//where the 'work' happends

   stages {
      stage('installing') {
         steps {
            echo 'installing node modules...'
            sh 'npm install'
           
         }
      }
     
     stage('build') {
         steps {
            echo 'testing application'
           sh 'ng serve'
         }
      }
     
     stage('deploy') {
         steps {
            echo 'deploy application'
         }
      }
   }
}

